## A pair of functions that solve matrix inversion using cache


## A function creating a special "matrix" object that can cache its inverse.
makeCacheMatrix <- function(x = matrix()) {
    im <- NULL ## initialise im (inverse matrix)
    set <- function(y) {   ## Define the function to sets value of the matrix 
        x <<- y
        im <<- NULL}
    get <- function() x   ## Define the function that returns value of the matrix x
    set_inversematrix <- function(inversematrix) im <<- inversematrix   ## Define the function to sets the value of the inverse matrix im
    get_inversematrix <- function() im   ## Define the function that returns value of the inverse matrix
    list(## Return list with the four functions
        set = set,
        get = get,
        set_inversematrix = set_inversematrix,
        get_inversematrix = get_inversematrix)}


## A function to solve the inverse of the matrix, using cached value if available
cacheSolve <- function(x, ...) {
    ## get value of the inverse matrix for x and if it exists, return its value
    im <- x$get_inversematrix()
    if(!is.null(im)) {
        message("Retrieving inverse matrix from cache")
        print(im)
        return(im)}
    ## if inverse matrix is not stored in the cache, solve its value using 'solve' function 
    message ("Calculating inverse matrix")
    data <- x$get()
    im <- solve(data, ...)
    print(im)
    x$set_inversematrix(im)
    im}


## Function to assist testing cacheSolve
testcacheSolve <- function (testmatrix = matrix(c(5,4,3,2),2,2)) {
    cat ('Functional test of the cacheSolve and makeCacheMatrix functions\n')
    cat ("---------------------------------------------------------------\n\n")
    # Print test inputs to the console
    cat ('Test Input:\n')
    print (testmatrix)
    cat ('\n')
    # Print expected outcomes
    cat ('Expected Outcomes:\n',
        'a) Inverse matrix generated by Iteration 1 of CacheSolve function has been calculated\n',
        'b) Inverse matrix generated by Iteration 2 of CacheSolve function has been retrieved from cache\n',
        'c) Inverse matrix generated by Iteration 3 of CacheSolve function has been retrieved from cache\n',
        'd) Inverse matrix generated by the built in solve function (outside CacheSolve function) has been generated\n',
        'e) Inverse matrices generated in Iteration 1,2,3 and the one generated without cacheSolve function are the same\n\n')
    # Execute tests and print out its results
    cat ('Test Output:\n')
    temp <- makeCacheMatrix(testmatrix) ## assign the 'cache' object to temp
    cat  ('a) Inverse matrix generated by CacheSolve function - Iteration 1\n')
    cacheSolve(temp) ## solve the inverse matrix using the cacheSolve (via temp variable). This should compute inverse matrix from scratch
    cat  ('\nb) Inverse matrix generated by CacheSolve function - iteration 2\n')
    cacheSolve(temp) ## repeat solving the inverse matrix using the cacheSolve. This should retrieve the inverse matrix from the cache
    cat ('\nc) Inverse matrix generated by CacheSolve function - iteration 3\n')
    cacheSolve(temp) ## repeat solving the inverse matrix using the cacheSolve. This should retrieve the inverse matrix from the cache
    cat ('\nd) Inverse matrix generated using solve() function outside CacheSolve:\n')
    print (solve (testmatrix))
    cat ('\ne) Please check manually that the inverse matrices generated by the test script are same.\n')
    }


# Body of the programme - trigger test function
testcacheSolve()