## Put comments here that give an overall description of what your
## functions do
## A pair of functions that cache the inverse of a matrix plus a test function
##

## Write a short comment describing this function
## A function creating a special "matrix" object that can cache its inverse.

makeCacheMatrix <- function(x = matrix()) {

  
  ## initialise im (inverse matrix)
  im <- NULL
  
  ## Define the function to sets value of the matrix (in 'makeCacheMatrix' environment) to the value of the 'set' function's argument
  ## The function also resets the corresponding inverse matrix (im) to NULL in case matrix has changed
  set <- function(y) {
    x <<- y
    im <<- NULL
  }
  
  ## Define the function that returns value of the matrix x
  get <- function() x
  
  ## Define the function to sets the value of the inverse matrix im (in the 'makeCacheMatrix' env)
  ## to the value of the argument passed to this ('set_inversematrix') nested function
  set_inversematrix <- function(inversematrix) im <<- inversematrix
  
  ## Define the function that returns value of the inverse matrix im (from 'makeCacheMatrix' env)
  get_inversematrix <- function() im
  
  ## Return list with the four functions
  list(set = set,
       get = get,
       set_inversematrix = set_inversematrix,
       get_inversematrix = get_inversematrix)
}


## Write a short comment describing this function
## A function to compute the inverse of the matrix returned by makeCacheMatrix above
## If the inverse has already been calculated (and the matrix has not changed),
## then the function retrieves the inverse from the cache.

cacheSolve <- function(x, ...) {
        ## Return a matrix that is the inverse of 'x'
  ## get value of the inverse matrix for x and return its value if it exists
  im <- x$get_inversematrix()
  if(!is.null(im)) { ## execute if inverse matrix not empty
    message("Retrieving inverse matrix from cache")
    print(im)
    return(im)
  }
  
  ## get value of x, compute the inverse matrix of x, store its value in the cache
  ## before returning value of the computed inverse matrix
  message ("Calculating inverse matrix")
  data <- x$get()
  im <- solve(data, ...)
  print(im)
  x$set_inversematrix(im)
  im
  }

## Function to assist testing. Output of the test function is to be verified manually
testcacheSolve <- function (testmatrix = matrix(c(5,4,3,2),2,2)) {
  print ("Test matrix:")
  print (testmatrix)
  print ("Inverse of the test matrix solved using the built-in 'solve' function:")
  print(solve (testmatrix)) ## This can be used to verify subsequent outputs
  temp <- makeCacheMatrix(testmatrix) ## assign the 'cache' object to temp
  print  ("Inverse of the test matrix solved using 'CacheSolve' function")
  cacheSolve(temp) ## solve the inverse matrix using the cacheSolve (via temp variable). This should compute inverse matrix from scratch
  cacheSolve(temp) ## repeat solving the inverse matrix using the cacheSolve. This should retrieve the inverse matrix from the cache
  cacheSolve(temp) ## repeat solving the inverse matrix using the cacheSolve. This should retrieve the inverse matrix from the cache
}

## Function to assist testing. Output of the test function is to be verified manually
testcacheSolve <- function (testmatrix = matrix(c(5,4,3,2),2,2)) {
  cat ('Functional test of the cacheSolve and makeCacheMatrix functions\n')
  cat ("---------------------------------------------------------------\n\n")
  cat ('Test Input:\n')
  print (testmatrix)
  cat ('\n')
  cat ('Expected Outcomes:\n',
       'a) Inverse matrix generated by Iteration 1 of CacheSolve function has been calculated\n',
       'b) Inverse matrix generated by Iteration 2 of CacheSolve function has been retrieved from cache\n',
       'c) Inverse matrix generated by Iteration 3 of CacheSolve function has been retrieved from cache\n',
       'd) Inverse matrix generated by the built in solve function (outside CacheSolve function) has been generated\n',
       'e) Inverse matrices generated in Iteration 1,2,3 and the one generated without cacheSolve function are the same\n\n')
  cat ('Test Output:\n')
  temp <- makeCacheMatrix(testmatrix) ## assign the 'cache' object to temp
  cat  ('a) Inverse matrix generated by CacheSolve function - Iteration 1\n')
  cacheSolve(temp) ## solve the inverse matrix using the cacheSolve (via temp variable). This should compute inverse matrix from scratch
  cat  ('\nb) Inverse matrix generated by CacheSolve function - iteration 2\n')
  cacheSolve(temp) ## repeat solving the inverse matrix using the cacheSolve. This should retrieve the inverse matrix from the cache
  cat ('\nc) Inverse matrix generated by CacheSolve function - iteration 3\n')
  cacheSolve(temp) ## repeat solving the inverse matrix using the cacheSolve. This should retrieve the inverse matrix from the cache
  cat ('\nd) Inverse matrix generated using solve() function outside CacheSolve:\n')
  print (solve (testmatrix))
  cat ('\ne) Please check manually that the inverse matrices generated by the test script are same.\n')
}

testcacheSolve()
